--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/creepies/MuteAssistant
build-by-default: true
branches:
- master
projects:
  MuteAssistant:
    path: ""
    libs:
     - src: jojoe77777/FormAPI/libFormAPI
       version: ^1.3
...
